### ISSUE TITLE
when runing to detector.detect(I, tagSize, cam, cMo_vec), there is a error 0x0000022A5E230250 处(位于 Puncture System.exe 中)引发的异常: 0xC0000005: 执行位置 0x0000022A5E230250 时发生访问冲突。

### ISSUE THREAD

**Issue by yangqingnian** [lagadic/visp#1190] opened 2023-07-07 02:24 UTC

**Comment by yangqingnian** [comment] 2023-07-07 02:33
please help me

**Comment by yangqingnian** [comment] 2023-07-07 02:47
@clairedune

**Comment by fspindle** [comment] 2023-07-13 08:02
To few info to provide help!

**Comment by yangqingnian** [comment] 2023-07-15 12:46
when i use visp to detect apriltag, the program will show error when running to detect(I,  tagSize, &cam,cMo_vec). i don't know how to solve it, help me!

**Comment by fspindle** [comment] 2023-07-17 08:05
Duplicate of #1203

**Closed by fspindle** 2023-07-17 08:05 UTC
